import type { NextPage } from 'next'
import React, { useEffect } from 'react'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { Button } from 'antd'
import { Store } from '../store'
import { useContext } from 'react'
import { ACTIONS } from '../store/actions'
import { Layout } from '../layout'

const Home: NextPage = () => {
  const { state, dispatch } = useContext(Store)

  useEffect(() => {
    console.log('state: ', state)
    console.log(dispatch)
  }, [state])

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          <Button
            type='primary'
            onClick={() => {
              console.log('im here1', ACTIONS.USER_AUTHORIZED)
              debugger
              dispatch({ type: ACTIONS.USER_AUTHORIZED, payload: true })
            }}
          >
            Button
          </Button>
        </main>
      </div>
    </Layout>
  )
}

export default Home
