import type { NextPage } from 'next'
import React, { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { Button } from 'antd'
import { Store } from '../store'
import { useContext } from 'react'
import { ACTIONS } from '../store/actions'

const Home: NextPage = () => {
  const { state, dispatch } = useContext(Store)

  useEffect(() => {
    console.log('state: ', state)
    console.log(dispatch)
  }, [state])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Button
          type='primary'
          onClick={() => {
            console.log('im here1', ACTIONS.USER_AUTHORIZED);
            debugger
            dispatch({ type: ACTIONS.USER_AUTHORIZED, payload: true })
          }}
        >
          Button
        </Button>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
